### PR TITLE
Custom .gitignore in app generation (Closes #80)

### LINKED ISSUE #80: dynamically generate .gitignore for new apps
The current implementation of .gitignore for new apps is a static file that makes assumptions about the names of the build and public directories, but since these can be configured by the user they could easily be incorrect.

This file should be dynamically generated to base the ignored directories off what the user selects when generating a new app.

### PR DESCRIPTION
**Pull request by dishad**
Automatically adds user's `publicFolder`  and `.build` locations to gitignore

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -404,6 +413,55 @@ module.exports = generators.Base.extend({
...
+            return self.gitIgnore;
+          };
+
+      return self.prompt(
+        [
+          {
+            when: whenIgnoring,
+            type: 'input',
+            name: 'gitIgnoreStream',
+            message: 'What location would you like you add to .gitignore?',
```
Comment (Autre31415) [inline generators/app/index.js]: Adding to the .gitignore at this point in app creation is pretty niche, moreso than setting the public and .build directories, and those don't have prompts.

I think it would be better to add gitignore as an option rather than a recursive prompt to keep things simple for this reason.

**Comment by Autre31415** [comment]
Since you're already deep into dynamically altering files based on the user's build and public folders it would be a good idea to also go ahead and dynamically alter these npm scripts based on those options as well: https://github.com/rooseveltframework/generator-roosevelt/blob/master/generators/app/templates/templatedPackage.json#L171

Both -dev and -prod have supervisor options in the scripts statically pointing to .build and public.

File: generators/app/index.js (hunk 1 above)
Comment (dishad) [inline generators/app/index.js]: So we can just prompt the user once for the .gitignore? Okay

**Comment by dishad** [comment]
I can add to the -dev and -prod arguments no problemo!

File: generators/app/index.js (hunk 1 above)
Comment (Autre31415) [inline generators/app/index.js]: Even simpler, just toss it into the options pile. That way it can be taken as an argument like all the other features which are considered too niche to prompt for.
